version: '3.8'

services:
  modbus-easyfire:
    container_name: modbus-easyfire
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MODBUS_HOST=${MODBUS_HOST}
      - MODBUS_PORT=${MODBUS_PORT}
      - MODBUS_UNIT_ID=${MODBUS_UNIT_ID}
      - HTTP_PORT=${HTTP_PORT}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
